# Generated by Django 2.0 on 2019-04-21 13:54

from django.db import migrations, models
import nids.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FullEvent',
            fields=[
                ('sid', nids.models.UnsignedIntegerField(primary_key=True, serialize=False)),
                ('cid', nids.models.UnsignedIntegerField()),
                ('signature', nids.models.UnsignedIntegerField()),
                ('sig_name', models.CharField(blank=True, max_length=255)),
                ('sig_class_id', nids.models.UnsignedIntegerField(blank=True)),
                ('sig_priority', nids.models.UnsignedIntegerField(blank=True)),
                ('timestamp', models.DateTimeField()),
                ('ip_src', nids.models.UnsignedIntegerField(blank=True)),
                ('ip_dst', nids.models.UnsignedIntegerField(blank=True)),
                ('ip_proto', models.IntegerField(blank=True)),
                ('port_src', nids.models.UnsignedIntegerField(blank=True)),
                ('port_dst', nids.models.UnsignedIntegerField(blank=True)),
            ],
            options={
                'db_table': 'fullevent',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.IntegerField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=20)),
                ('role_desc', models.CharField(max_length=75)),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('usr_id', models.IntegerField(primary_key=True, serialize=False)),
                ('usr_login', models.CharField(max_length=25)),
                ('usr_pwd', models.CharField(max_length=32)),
                ('usr_name', models.CharField(max_length=75)),
                ('role_id', models.IntegerField()),
                ('usr_enabled', models.IntegerField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
